fix: rename /api-clients/access-control-systems -> /api-clients/acs
seamapi/docs pull request #308
Opened 2024-08-16 07:54 UTC by mikewuu

2024-08-16 19:09 UTC, razor-x requested changes
We need to do this for every page under the api-clients folder (not just ACS). This is because of how gitbook enforces the path matching.

2024-08-16 19:09 UTC, razor-x commented on .gitbook.yaml
> +  api-clients/access-control-systems/systems/get-system: api-clients/acs/systems/get-system.md
```suggestion
  api-clients/access-control-systems/systems/get-system: api-clients/acs/systems/get.md
```

Etc.

2024-08-16 19:09 UTC, razor-x commented on docs/SUMMARY.md
> +    * [List Users](api-clients/acs/users/list-users.md)
```suggestion
    * [List Users](api-clients/acs/users/list.md)
```
Etc.

2024-08-19 06:50 UTC, mikewuu commented
@razor-x renamed everything in **/api-clients**. Wasn't 100% on the naming for some of the routes, specifically ones that include other resource names, like **list-credentials-with-access-to-an-entrance**.

See https://github.com/seamapi/docs/pull/308/files#diff-3bdea6261687f749bccd68763ce01cfe6249305137f746ef6ef7c3f7eadebd0d for all the renamings

2024-08-19 13:35 UTC, mikewuu commented on docs/SUMMARY.md
> +    * [List Users](api-clients/acs/users/list-users.md)
updated in https://github.com/seamapi/docs/pull/308/commits/b01416b3487f42a305527833db477602501fe6ed

2024-08-19 18:10 UTC, razor-x commented
@mikewuu All the routes need to match the API exactly, i.e., every file is 1to1 with and API route. 


```
api-clients/acs/entrances/list-credentials-with-access-to-an-entrance.md => api-clients/acs/entrances/list_credentials_with_access.md
```

Additionally, we need all the paths to match the API, so for example, these still need to be fixed, etc.


```
docs/api-clients/devices/list-unmanaged.md => docs/api-clients/devices/unmanaged/list.md
docs/api-clients/user-identities/add-an-acs-user.md => docs/api-clients/user_identities/add_acs_user.md
... any file that does not match the API route it documents exactly
```

2024-08-20 19:22 UTC, mikewuu commented
@razor-x , closing in favor of #312  as this PR got stale.

2024-08-20 19:22 UTC, closed without merging