feat(acs/entrances): add code samples
seamapi/docs pull request #383
Opened 2024-10-15 13:00 UTC by mikewuu

Partially addresses https://github.com/seamapi/docs/issues/358

2024-10-24 07:44 UTC, DebbieAtSeam requested changes

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +- title: List Entrances
```suggestion
- title: List entrances
```

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +  description: Returns a list of all [entrances](https://docs.seam.co/latest/capability-guides/access-systems/retrieving-entrance-details).
```suggestion
  description: To filter the list of entrances, specify the desired `acs_system_id` or `acs_user_id`.
```

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +- title: Get an Entrance
```suggestion
- title: Get an entrance
```

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +  description: Returns a specified [entrance](https://docs.seam.co/latest/capability-guides/access-systems/retrieving-entrance-details).
```suggestion
  description: Specify the `acs_entrance_id` of the entrance that you want to retrieve.
```

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +- title: List Credentials with Access to an Entrance
```suggestion
- title: List credentials with access to an entrance
```

2024-10-24 07:44 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-entrances.yaml
> +  description: Returns a list of all [credentials](https://docs.seam.co/latest/capability-guides/access-systems/managing-credentials) with access to a specified [entrance](https://docs.seam.co/latest
```suggestion
  description: Specify the `acs_entrance_id` to return all credentials that grant access to the specified entrance.
```

2024-10-29 20:37 UTC, DebbieAtSeam approved these changes

2024-10-30 06:30 UTC, razor-x approved these changes

2024-10-30 17:58 UTC, merged