Add acs access group code sample definitions
seamapi/docs pull request #384
Opened 2024-10-15 17:04 UTC by andrii-balitskyi

2024-10-24 06:14 UTC, DebbieAtSeam requested changes

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +- title: Add a user to an access group
```suggestion
- title: Add an ACS user to an access group
```

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +  description: Specify the `acs_access_group_id` and `acs_user_id` to add a user to an access group.
```suggestion
  description: Specify the `acs_access_group_id` and `acs_user_id` to add an ACS user to an access group.
```

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +- title: Remove a user from an access group
```suggestion
- title: Remove an ACS user from an access group
```

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +  description: Specify the `acs_access_group_id` and `acs_user_id` to remove a user from an access group.
```suggestion
  description: Specify the `acs_access_group_id` and `acs_user_id` to remove an ACS user from an access group.
```

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +- title: List users in an access group
```suggestion
- title: List ACS users in an access group
```

2024-10-24 06:14 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-access-groups.yaml
> +  description: Specify the `acs_access_group_id` to retrieve all users in an access group.
```suggestion
  description: Specify the `acs_access_group_id` to retrieve all ACS users in an access group.
```

2024-10-25 15:20 UTC, DebbieAtSeam approved these changes

2024-10-28 05:58 UTC, razor-x approved these changes

2024-10-29 14:54 UTC, merged