Add acs credentials code sample definitions
seamapi/docs pull request #388
Opened 2024-10-17 15:16 UTC by andrii-balitskyi

2024-10-24 06:32 UTC, DebbieAtSeam requested changes

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Create a Credential for a User
```suggestion
- title: Create a credential for an ACS user
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Creates a new credential for a specified ACS user.
```suggestion
  description: Specify the `acs_user_id` and `access_method` to create a new credential. You can also specify additional parameters, depending on the `access_method`.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Assign a Credential to a User
```suggestion
- title: Assign a credential to an ACS user
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Assigns a specified credential to a specified ACS user.
```suggestion
  description: Specify the desired `acs_user_id` and `acs_credential_id` to assign a credential to an ACS user.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: List Credentials
```suggestion
- title: List credentials
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Returns a list of all credentials.
```suggestion
  description: Filter the list of returned credentials by `acs_user_id`, `acs_system_id`, or `user_identity_id`. You can also include `is_multi_phone_sync_credential`.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Get a Credential
```suggestion
- title: Get a credential
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Returns a specified credential.
```suggestion
  description: Specify the `acs_credential_id` of the credential that you want to retrieve.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Update a Credential
```suggestion
- title: Update a credential
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Updates the code for a specified credential.
```suggestion
  description: Specify the desired `acs_credential_id` and updated `code` to update the credential.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Unassign a Credential from a User
```suggestion
- title: Unassign a credential from an ACS user
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Unassigns a specified credential from a specified ACS user.
```suggestion
  description: Specify the desired `acs_user_id` and `acs_credential_id` to unassign the specified credential from the specified ACS user.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: Delete a Credential
```suggestion
- title: Delete a credential
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Deletes a specified credential.
```suggestion
  description: Specify the desired `acs_credential_id` to delete the specified credential.
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +- title: List Accessible Entrances
```suggestion
- title: List accessible entrances
```

2024-10-24 06:32 UTC, DebbieAtSeam commented on src/data/code-sample-definitions/acs-credentials.yaml
> +  description: Returns a list of all entrances to which a credential grants access.
```suggestion
  description: Specify the `acs_credential_id` for which you want to retrieve all entrances to which the credential grants access.
```

2024-10-25 15:21 UTC, DebbieAtSeam approved these changes

2024-10-28 05:58 UTC, razor-x approved these changes

2024-10-29 14:54 UTC, merged